version: '3'

services:
    php:
        container_name: "php-fpm-calculator"
        build:
            context: ./infra-docker/php
        volumes:
            - ./:/var/www
    nginx:
        container_name: "nginx-calculator"
        build:
            context: ./infra-docker/nginx
        volumes:
            - ./:/var/www
            - ./infra-docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./infra-docker/logs:/var/log
        depends_on:
            - php
        ports:
            - "10006:80"
