<?php

namespace ContainerZvFKYnA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JX7eP5wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jX7eP5w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jX7eP5w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calculatorService' => ['privates', 'App\\Service\\CalculatorService', 'getCalculatorServiceService', true],
            'expressionValidator' => ['privates', 'App\\Validator\\ExpressionValidator', 'getExpressionValidatorService', true],
        ], [
            'calculatorService' => 'App\\Service\\CalculatorService',
            'expressionValidator' => 'App\\Validator\\ExpressionValidator',
        ]);
    }
}
