<?php

namespace ContainerZvFKYnA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculatorServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CalculatorService' shared autowired service.
     *
     * @return \App\Service\CalculatorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CalculatorService.php';

        return $container->privates['App\\Service\\CalculatorService'] = new \App\Service\CalculatorService();
    }
}
