<?php

namespace ContainerZvFKYnA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpressionValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\ExpressionValidator' shared autowired service.
     *
     * @return \App\Validator\ExpressionValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validator/AbstractValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/ValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/ExpressionValidator.php';

        return $container->privates['App\\Validator\\ExpressionValidator'] = new \App\Validator\ExpressionValidator(($container->services['.container.private.validator'] ?? $container->load('get_Container_Private_ValidatorService')));
    }
}
