<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZvFKYnA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZvFKYnA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZvFKYnA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZvFKYnA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZvFKYnA\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZvFKYnA',
    'container.build_id' => '1be0a449',
    'container.build_time' => 1614855785,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZvFKYnA');
